name: Build and Test Maven Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '30 17 * * 2,4' # 11 PM IST on Tuesday and Thursday

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Clean the project
      - name: Clean with Maven
        run: mvn -f addition/pom.xml clean

      # Compile the project
      - name: Compile with Maven
        run: mvn -f addition/pom.xml compile

      # Run tests
      - name: Run tests
        run: mvn -f addition/pom.xml test

      # Package the JAR
      - name: Package JAR with Maven
        run: mvn -f addition/pom.xml package