name: Orchestrator Workflow

on:
  workflow_dispatch: # Allow manual triggering of the orchestrator workflow

permissions:
  actions: write
  contents: read

jobs:
  project-one:
    name: Run Project-One Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Project-One Workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.WORKFLOW_PAT }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'kvs-org',
              repo: 'project-one',
              workflow_id: 'maven-package.yml',
              ref: 'main'
            });

  project-two:
    name: Run Project-Two Workflow
    runs-on: ubuntu-latest
    needs: [project-one] # Wait for project-one to complete
    steps:
      - name: Trigger Project-Two Workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.WORKFLOW_PAT }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'kvs-org',
              repo: 'project-two',
              workflow_id: 'maven-package.yml',
              ref: 'main'
            });

  project-three:
    name: Run Project-Three Workflow
    runs-on: ubuntu-latest
    needs: [project-one, project-two] # Wait for project-one and project-two to complete
    steps:
      - name: Trigger Project-Three Workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.WORKFLOW_PAT }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'kvs-org',
              repo: 'project-three',
              workflow_id: 'maven-package.yml',
              ref: 'main'
            });

  project-four:
    name: Run Project-Four Workflow
    runs-on: ubuntu-latest
    needs: [project-one, project-two, project-three] # Wait for project-one, project-two, and project-three to complete
    steps:
      - name: Trigger Project-Four Workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.WORKFLOW_PAT }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'kvs-org',
              repo: 'project-four',
              workflow_id: 'maven-package.yml',
              ref: 'main'
            });
